import json
import os
from io import BytesIO
from typing import Dict, List

from openai import (
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    OpenAI,
    RateLimitError,
)


SCRIPTWRITER_INSTRUCTIONS = (
    "You are an expert presentation scriptwriter. Write complete, polished English narration "
    "that a presenter can memorize and repeat almost verbatim. Follow the slide order exactly. "
    "Use the source document context to add accurate examples and explanations. Do not invent facts."
)


def generate_narrative(
    source_name: str,
    source_bytes: bytes,
    deck_name: str,
    deck_bytes: bytes,
    audience: str,
    tone: str,
    guidance: str,
    model: str,
    context: Dict,
    api_key: str = "",
    include_files: bool = False,
) -> Dict:
    active_api_key = api_key or os.getenv("OPENAI_API_KEY")
    if not active_api_key:
        raise RuntimeError("OpenAI API key is required. Paste a key into the app before generating.")
    return generate_with_openai(
        source_name,
        source_bytes,
        deck_name,
        deck_bytes,
        audience,
        tone,
        guidance,
        model,
        context,
        active_api_key,
        include_files,
    )


def generate_with_openai(
    source_name: str,
    source_bytes: bytes,
    deck_name: str,
    deck_bytes: bytes,
    audience: str,
    tone: str,
    guidance: str,
    model: str,
    context: Dict,
    api_key: str,
    include_files: bool,
) -> Dict:
    client = OpenAI(api_key=api_key, timeout=300.0, max_retries=2)

    try:
        if include_files:
            use_slide_images = context_has_slide_images(context)
            uploaded_files = upload_input_files(
                client,
                source_name,
                source_bytes,
                deck_name,
                deck_bytes,
                include_deck=not use_slide_images,
            )
            result = generate_batched_responses_narrative(
                client,
                model,
                audience,
                tone,
                guidance,
                context,
                uploaded_files,
                use_slide_images=use_slide_images,
            )
        else:
            result = generate_batched_chat_narrative(client, model, audience, tone, guidance, context)
    except AuthenticationError as exc:
        raise RuntimeError("OpenAI rejected the API key. Check that the key is valid and has API access.") from exc
    except RateLimitError as exc:
        raise RuntimeError("OpenAI rate-limited the request. Try again later or choose a smaller model.") from exc
    except BadRequestError as exc:
        raise RuntimeError(f"OpenAI could not process the request: {extract_openai_message(exc)}") from exc
    except (APIConnectionError, APITimeoutError) as exc:
        if model != "gpt-4o-mini":
            try:
                result = generate_batched_chat_narrative(client, "gpt-4o-mini", audience, tone, guidance, context)
                result["model"] = "gpt-4o-mini"
                result.setdefault("notices", [])
                result["notices"].insert(
                    0,
                    "The selected model connection failed, so OpenAI generation was retried with GPT-4o mini.",
                )
                return result
            except (APIConnectionError, APITimeoutError) as final_exc:
                raise RuntimeError(
                    "OpenAI connection failed even with streaming GPT-4o mini requests."
                ) from final_exc
        raise RuntimeError("OpenAI connection failed even with one-slide GPT-4o mini requests.") from exc
    except APIError as exc:
        raise RuntimeError(f"OpenAI returned an API error: {extract_openai_message(exc)}") from exc

    result["mode"] = "llm"
    result["model"] = model
    result.setdefault("notices", [])
    if include_files:
        if context_has_slide_images(context):
            result["notices"].insert(
                0,
                "Generated by OpenAI using the uploaded source document plus each slide's visual image.",
            )
        else:
            result["notices"].insert(0, "Generated by OpenAI using uploaded original files plus extracted slide context.")
    else:
        result["notices"].insert(0, "Generated by OpenAI from extracted document and slide text.")
    return result


def upload_input_files(
    client: OpenAI,
    source_name: str,
    source_bytes: bytes,
    deck_name: str,
    deck_bytes: bytes,
    include_deck: bool = True,
) -> List[Dict]:
    files = [{"type": "input_file", "file_id": upload_file(client, source_name, source_bytes).id}]
    if include_deck:
        files.append({"type": "input_file", "file_id": upload_file(client, deck_name, deck_bytes).id})
    return files


def upload_file(client: OpenAI, filename: str, data: bytes):
    stream = BytesIO(data)
    stream.name = filename
    return client.files.create(file=stream, purpose="user_data")


def generate_batched_responses_narrative(
    client: OpenAI,
    model: str,
    audience: str,
    tone: str,
    guidance: str,
    context: Dict,
    uploaded_files: List[Dict],
    use_slide_images: bool,
) -> Dict:
    slides = context.get("slides") or []
    if not slides:
        slides = [{"slide_number": 1, "title": "Presentation", "text": "", "notes": ""}]

    all_slides = []
    raw_texts = []
    continuity_memory = []
    for batch in chunked(slides, 1):
        prompt = build_prompt(
            audience,
            tone,
            guidance,
            context,
            batch,
            include_original_file_note=True,
            use_slide_images=use_slide_images,
            continuity_memory=continuity_memory,
        )
        content = build_responses_content(uploaded_files, batch, prompt, use_slide_images)
        response = client.responses.create(
            model=model,
            instructions=SCRIPTWRITER_INSTRUCTIONS,
            input=[{"role": "user", "content": content}],
        )
        text = getattr(response, "output_text", "") or ""
        raw_texts.append(text)
        parsed = parse_json_response(text)
        if parsed and isinstance(parsed.get("slides"), list):
            aligned = align_generated_slides(parsed["slides"], batch)
            all_slides.extend(aligned)
            continuity_memory.extend(build_memory_entries(aligned))

    if all_slides:
        return {"slides": normalize_slides(all_slides, slides), "notices": []}
    return {
        "mode": "llm",
        "model": model,
        "slides": [],
        "raw_text": "\n\n".join(raw_texts),
        "notices": ["OpenAI returned prose rather than structured JSON, so the raw response is shown."],
    }


def generate_batched_chat_narrative(
    client: OpenAI,
    model: str,
    audience: str,
    tone: str,
    guidance: str,
    context: Dict,
) -> Dict:
    slides = context.get("slides") or []
    if not slides:
        slides = [{"slide_number": 1, "title": "Presentation", "text": "", "notes": ""}]

    all_slides = []
    raw_texts = []
    continuity_memory = []
    for batch in chunked(slides, 1):
        prompt = build_prompt(
            audience,
            tone,
            guidance,
            context,
            batch,
            include_original_file_note=False,
            use_slide_images=False,
            continuity_memory=continuity_memory,
        )
        text = create_chat_completion(client, model, prompt)
        raw_texts.append(text)
        parsed = parse_json_response(text)
        if parsed and isinstance(parsed.get("slides"), list):
            aligned = align_generated_slides(parsed["slides"], batch)
            all_slides.extend(aligned)
            continuity_memory.extend(build_memory_entries(aligned))

    if all_slides:
        return {"slides": normalize_slides(all_slides, slides), "notices": []}
    return {
        "mode": "llm",
        "model": model,
        "slides": [],
        "raw_text": "\n\n".join(raw_texts),
        "notices": ["OpenAI returned prose rather than structured JSON, so the raw response is shown."],
    }


def create_chat_completion(client: OpenAI, model: str, prompt: str) -> str:
    messages = [
        {"role": "system", "content": SCRIPTWRITER_INSTRUCTIONS},
        {"role": "user", "content": prompt},
    ]
    try:
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            response_format={"type": "json_object"},
            max_completion_tokens=1200,
        )
    except BadRequestError:
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            max_completion_tokens=1200,
        )
    return response.choices[0].message.content or ""


def build_prompt(
    audience: str,
    tone: str,
    guidance: str,
    context: Dict,
    slides: List[Dict],
    include_original_file_note: bool,
    use_slide_images: bool,
    continuity_memory: List[Dict],
) -> str:
    slide_outline = json.dumps(compact_slides(slides), ensure_ascii=False, indent=2)
    memory_outline = json.dumps(compact_memory(continuity_memory), ensure_ascii=False, indent=2)
    source_preview = first_words(context.get("source_preview", ""), 500)
    extra = f"\nAdditional presenter guidance: {guidance}" if guidance else ""
    slide_numbers = ", ".join(str(slide.get("slide_number", "")) for slide in slides)
    exact_json_items = ", ".join(str(slide.get("slide_number", "")) for slide in slides)
    if include_original_file_note and use_slide_images:
        file_note = (
            "The original source document is attached, and the current slide's image is attached in this request. "
            "Use the current slide image as the primary source for slide-specific content, including screenshots, diagrams, labels, tables, and layout. "
            "Do not infer the current slide from other deck slides."
        )
    elif include_original_file_note:
        file_note = (
            "The original source document and slide deck files are attached. Use them to interpret visual slide content, screenshots, diagrams, and layout. The deck contains other slides too, but you must ignore every slide except the slide number listed below."
        )
    else:
        file_note = "Use the extracted source document text as the evidence base and the extracted slide text as the slide order."
    return f"""
Create the English speaking narrative for slides {slide_numbers}.

Audience type: {audience}
Required tone: {tone}{extra}

{file_note}
For each slide in this batch, write a ready-to-deliver script, not bullet notes and not coaching guidance.
The presenter should be able to memorize the narrative and repeat it aloud with little or no added context.

Continuity rules:
- Use the prior slide context below only to create smooth transitions and avoid repeating the same explanation.
- The current slide must still drive the content. Do not regenerate, summarize, or revise prior slides.
- If useful, briefly refer back to the immediately previous slide, but keep the new slide's script specific and self-contained.

Strict slide-numbering rules:
- Return exactly {len(slides)} item(s) in the "slides" array.
- The only allowed slide_number value(s) are: {exact_json_items}.
- Do not return slide 1 or slide 2 unless those exact numbers are listed above.
- Do not summarize, repeat, or include any slide outside this current slide batch.
- Do not reuse a generic script from earlier or later slides. The narrative must be specific to the current slide's title, image, labels, and visual content.

Narrative requirements:
- Write 2 to 3 natural paragraphs per content slide.
- Aim for roughly 100 to 150 words per content slide.
- Build the explanation, context, transitions, and examples directly into the narrative.
- Use smooth transitions between slides. Avoid opening a slide narrative with generic phrases like "This slide shows..." or "This slide is about..."
- Do not say "the presenter can mention" or "you may want to explain"; just write the words the presenter should say.
- Use conversational spoken English while matching the requested tone.
- Stay faithful to the provided source and slide text.

Return only valid JSON in this exact shape:
{{
  "slides": [
    {{
      "slide_number": 1,
      "slide_title": "Title from the deck",
      "narrative": "Full memorization-ready speaker script for this slide.",
      "delivery_note": "Short coaching note for pacing or emphasis.",
      "estimated_time": "60-90 sec",
      "source_alignment": "Brief note about what source point this slide is grounded in."
    }}
  ]
}}

Current slide batch:
{slide_outline}

Prior slide context:
{memory_outline}

Source document excerpt:
{source_preview}
""".strip()


def build_responses_content(
    uploaded_files: List[Dict],
    slides: List[Dict],
    prompt: str,
    use_slide_images: bool,
) -> List[Dict]:
    content = list(uploaded_files)
    if use_slide_images:
        for slide in slides:
            for image in (slide.get("images") or [])[:3]:
                data_url = image.get("data_url")
                if data_url:
                    content.append({"type": "input_image", "image_url": data_url, "detail": "high"})
    content.append({"type": "input_text", "text": prompt})
    return content


def context_has_slide_images(context: Dict) -> bool:
    return any(slide.get("images") for slide in context.get("slides") or [])


def build_memory_entries(slides: List[Dict]) -> List[Dict]:
    entries = []
    for slide in slides:
        narrative = slide.get("narrative", "")
        entries.append(
            {
                "slide_number": slide.get("slide_number"),
                "slide_title": slide.get("slide_title") or f"Slide {slide.get('slide_number', '')}",
                "main_point": first_sentence(narrative) or first_words(narrative, 30),
                "closing_idea": last_sentence(narrative) or first_words(narrative, 30),
            }
        )
    return entries


def compact_memory(memory: List[Dict]) -> List[Dict]:
    if not memory:
        return []

    recent = memory[-4:]
    earlier = memory[:-4]
    compact = []
    if earlier:
        compact.append(
            {
                "earlier_slides": ", ".join(
                    f"{item.get('slide_number')}: {item.get('slide_title', 'Untitled')}" for item in earlier
                ),
                "use": "High-level roadmap only; do not repeat these slides.",
            }
        )
    for item in recent:
        compact.append(
            {
                "slide_number": item.get("slide_number"),
                "slide_title": item.get("slide_title", ""),
                "main_point": first_words(item.get("main_point", ""), 35),
                "closing_idea": first_words(item.get("closing_idea", ""), 35),
            }
        )
    return compact


def chunked(items: List[Dict], size: int) -> List[List[Dict]]:
    return [items[index : index + size] for index in range(0, len(items), size)]


def compact_slides(slides: List[Dict]) -> List[Dict]:
    compact = []
    for slide in slides:
        compact.append(
            {
                "slide_number": slide.get("slide_number"),
                "title": slide.get("title", ""),
                "text": first_words(slide.get("text", ""), 120),
                "notes": first_words(slide.get("notes", ""), 70),
            }
        )
    return compact


def normalize_slides(generated_slides: List[Dict], expected_slides: List[Dict]) -> List[Dict]:
    best_by_number = {}
    for item in generated_slides:
        number = coerce_slide_number(item.get("slide_number"))
        if number is None:
            continue
        item["slide_number"] = number
        current = best_by_number.get(number)
        if not current or len(item.get("narrative", "")) > len(current.get("narrative", "")):
            best_by_number[number] = item

    normalized = []
    for expected in expected_slides:
        number = expected.get("slide_number")
        if number in best_by_number:
            normalized.append(best_by_number[number])
    return normalized


def align_generated_slides(generated_slides: List[Dict], expected_batch: List[Dict]) -> List[Dict]:
    expected_numbers = [slide.get("slide_number") for slide in expected_batch]
    expected_numbers = [number for number in expected_numbers if number is not None]
    aligned = []
    used = set()

    for item in generated_slides:
        number = coerce_slide_number(item.get("slide_number"))
        if number in expected_numbers and number not in used:
            fixed = dict(item)
            fixed["slide_number"] = number
            aligned.append(fixed)
            used.add(number)

    remaining_items = [item for item in generated_slides if item not in aligned]
    for expected_number, item in zip((n for n in expected_numbers if n not in used), remaining_items):
        fixed = dict(item)
        fixed["slide_number"] = expected_number
        if not fixed.get("slide_title"):
            match = next((slide for slide in expected_batch if slide.get("slide_number") == expected_number), {})
            fixed["slide_title"] = match.get("title") or f"Slide {expected_number}"
        aligned.append(fixed)
        used.add(expected_number)

    return sorted(aligned, key=lambda item: item.get("slide_number", 0))


def coerce_slide_number(value):
    if isinstance(value, int):
        return value
    if isinstance(value, float) and value.is_integer():
        return int(value)
    if isinstance(value, str):
        import re

        match = re.search(r"\d+", value)
        if match:
            return int(match.group(0))
    return None


def extract_openai_message(exc: Exception) -> str:
    response = getattr(exc, "response", None)
    if response is not None:
        try:
            payload = response.json()
            message = payload.get("error", {}).get("message")
            if message:
                return message
        except Exception:
            pass
    return str(exc)


def parse_json_response(text: str) -> Dict:
    if not text:
        return {}
    candidates = [text.strip()]
    if "```" in text:
        fenced = text.split("```")
        candidates.extend(part.replace("json", "", 1).strip() for part in fenced if "{" in part)
    start = text.find("{")
    end = text.rfind("}")
    if start >= 0 and end > start:
        candidates.append(text[start : end + 1])
    for candidate in candidates:
        try:
            parsed = json.loads(candidate)
        except json.JSONDecodeError:
            continue
        if isinstance(parsed, dict) and isinstance(parsed.get("slides"), list):
            return parsed
    return {}


def first_words(text: str, count: int) -> str:
    words = (text or "").replace("\n", " ").split()
    return " ".join(words[:count])


def first_sentence(text: str) -> str:
    sentences = split_sentences(text)
    return sentences[0] if sentences else ""


def last_sentence(text: str) -> str:
    sentences = split_sentences(text)
    return sentences[-1] if sentences else ""


def split_sentences(text: str) -> List[str]:
    import re

    cleaned = re.sub(r"\s+", " ", text or "").strip()
    if not cleaned:
        return []
    return [sentence.strip() for sentence in re.split(r"(?<=[.!?])\s+", cleaned) if sentence.strip()]
