import json
import os
from typing import Dict, List

from openai import (
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    OpenAI,
    RateLimitError,
)

from narrator import (
    SCRIPTWRITER_INSTRUCTIONS,
    compact_slides,
    context_has_slide_images,
    extract_openai_message,
    first_words,
    normalize_slides,
    parse_json_response,
    upload_input_files,
)


def generate_narrative(
    source_name: str,
    source_bytes: bytes,
    deck_name: str,
    deck_bytes: bytes,
    audience: str,
    tone: str,
    guidance: str,
    model: str,
    context: Dict,
    api_key: str = "",
    include_files: bool = False,
) -> Dict:
    active_api_key = api_key or os.getenv("OPENAI_API_KEY")
    if not active_api_key:
        raise RuntimeError("OpenAI API key is required. Paste a key into the app before generating.")
    return generate_with_openai(
        source_name,
        source_bytes,
        deck_name,
        deck_bytes,
        audience,
        tone,
        guidance,
        model,
        context,
        active_api_key,
        include_files,
    )


def generate_with_openai(
    source_name: str,
    source_bytes: bytes,
    deck_name: str,
    deck_bytes: bytes,
    audience: str,
    tone: str,
    guidance: str,
    model: str,
    context: Dict,
    api_key: str,
    include_files: bool,
) -> Dict:
    client = OpenAI(api_key=api_key, timeout=600.0, max_retries=2)

    try:
        if include_files:
            uploaded_files = upload_input_files(client, source_name, source_bytes, deck_name, deck_bytes)
            result = generate_full_context_responses_narrative(
                client, model, audience, tone, guidance, context, uploaded_files
            )
        else:
            result = generate_full_context_chat_narrative(client, model, audience, tone, guidance, context)
    except AuthenticationError as exc:
        raise RuntimeError("OpenAI rejected the API key. Check that the key is valid and has API access.") from exc
    except RateLimitError as exc:
        raise RuntimeError("OpenAI rate-limited the request. Try again later or choose a smaller model.") from exc
    except BadRequestError as exc:
        raise RuntimeError(f"OpenAI could not process the full-context request: {extract_openai_message(exc)}") from exc
    except (APIConnectionError, APITimeoutError) as exc:
        raise RuntimeError("OpenAI connection failed during the full-deck request.") from exc
    except APIError as exc:
        raise RuntimeError(f"OpenAI returned an API error: {extract_openai_message(exc)}") from exc

    result["mode"] = "llm"
    result["model"] = model
    result.setdefault("notices", [])
    if include_files:
        if context_has_slide_images(context):
            result["notices"].insert(
                0,
                "Full-context version: generated by OpenAI from the uploaded source/deck files plus all slide images in one request.",
            )
        else:
            result["notices"].insert(
                0,
                "Full-context version: generated by OpenAI from the whole uploaded source document and slide deck in one request.",
            )
    else:
        result["notices"].insert(
            0,
            "Full-context version: generated by OpenAI from all extracted document and slide text in one request.",
        )
    return result


def generate_full_context_responses_narrative(
    client: OpenAI,
    model: str,
    audience: str,
    tone: str,
    guidance: str,
    context: Dict,
    uploaded_files: List[Dict],
) -> Dict:
    slides = expected_slides(context)
    use_slide_images = context_has_slide_images(context)
    prompt = build_full_context_prompt(
        audience,
        tone,
        guidance,
        context,
        include_original_files=True,
        use_slide_images=use_slide_images,
    )
    content = build_full_context_content(uploaded_files, slides, prompt, use_slide_images)
    response = create_responses_output(client, model, content)
    text = getattr(response, "output_text", "") or ""
    parsed = parse_json_response(text)
    if parsed and isinstance(parsed.get("slides"), list):
        return {"slides": normalize_slides(parsed["slides"], slides), "notices": []}
    return raw_response(model, text)


def generate_full_context_chat_narrative(
    client: OpenAI,
    model: str,
    audience: str,
    tone: str,
    guidance: str,
    context: Dict,
) -> Dict:
    slides = expected_slides(context)
    prompt = build_full_context_prompt(
        audience,
        tone,
        guidance,
        context,
        include_original_files=False,
        use_slide_images=False,
    )
    text = create_chat_output(client, model, prompt)
    parsed = parse_json_response(text)
    if parsed and isinstance(parsed.get("slides"), list):
        return {"slides": normalize_slides(parsed["slides"], slides), "notices": []}
    return raw_response(model, text)


def create_responses_output(client: OpenAI, model: str, content: List[Dict]):
    try:
        return client.responses.create(
            model=model,
            instructions=SCRIPTWRITER_INSTRUCTIONS,
            input=[{"role": "user", "content": content}],
            max_output_tokens=9000,
        )
    except BadRequestError as exc:
        message = extract_openai_message(exc).lower()
        if "max_output_tokens" not in message and "max output" not in message:
            raise
        return client.responses.create(
            model=model,
            instructions=SCRIPTWRITER_INSTRUCTIONS,
            input=[{"role": "user", "content": content}],
        )


def create_chat_output(client: OpenAI, model: str, prompt: str) -> str:
    messages = [
        {"role": "system", "content": SCRIPTWRITER_INSTRUCTIONS},
        {"role": "user", "content": prompt},
    ]
    try:
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            response_format={"type": "json_object"},
            max_completion_tokens=9000,
        )
    except BadRequestError as exc:
        message = extract_openai_message(exc).lower()
        if "max" in message or "response_format" in message:
            response = client.chat.completions.create(model=model, messages=messages)
        else:
            raise
    return response.choices[0].message.content or ""


def build_full_context_prompt(
    audience: str,
    tone: str,
    guidance: str,
    context: Dict,
    include_original_files: bool,
    use_slide_images: bool,
) -> str:
    slides = expected_slides(context)
    slide_count = len(slides)
    slide_outline = json.dumps(compact_slides(slides), ensure_ascii=False, indent=2)
    source_preview = first_words(context.get("source_preview", ""), 1000)
    extra = f"\nAdditional presenter guidance: {guidance}" if guidance else ""
    if include_original_files and use_slide_images:
        file_note = (
            "The complete original source document and original slide deck are attached. "
            "In addition, every slide image is attached in order and labeled by slide number. "
            "Use those labeled slide images as the primary source for visual slide content."
        )
    elif include_original_files:
        file_note = (
            "The complete original source document and complete original slide deck are attached. Inspect the full deck visually and use the source document for accurate context."
        )
    else:
        file_note = "Use the extracted source document text and extracted slide text as the evidence base."
    return f"""
Create a complete English speaker narrative for the entire slide deck in one full-context pass.

Audience type: {audience}
Required tone: {tone}{extra}

{file_note}

Full-context generation rules:
- Return exactly {slide_count} slide item(s), one for every slide in the deck.
- Follow the deck order exactly from slide 1 through slide {slide_count}.
- Use the full deck context to create natural continuity across slides.
- Do not merge slides, skip slides, duplicate slides, or create multiple alternative versions for any slide.
- Each slide narrative must be specific to that slide's visual content, title, labels, table, screenshot, or diagram.
- For image-only slides, use the attached labeled slide image for that slide instead of relying on extracted text.

Narrative requirements:
- Write 2 to 3 natural paragraphs per content slide.
- Aim for roughly 100 to 150 words per content slide.
- Build explanation, context, transitions, and examples directly into the script.
- Use smooth transitions between slides. Avoid opening a slide narrative with generic phrases like "This slide shows..." or "This slide is about..."
- Do not say "the presenter can mention" or "you may want to explain"; write the words the presenter should say.
- Stay faithful to the source document and the slide deck. Do not invent findings.

Return only valid JSON in this exact shape:
{{
  "slides": [
    {{
      "slide_number": 1,
      "slide_title": "Title from the deck",
      "narrative": "Full memorization-ready speaker script for this slide.",
      "delivery_note": "Short coaching note for pacing or emphasis.",
      "estimated_time": "60-90 sec",
      "source_alignment": "Brief note about what source point this slide is grounded in."
    }}
  ]
}}

Extracted slide outline:
{slide_outline}

Source document excerpt:
{source_preview}
""".strip()


def build_full_context_content(
    uploaded_files: List[Dict],
    slides: List[Dict],
    prompt: str,
    use_slide_images: bool,
) -> List[Dict]:
    content = list(uploaded_files)
    if use_slide_images:
        content.append(
            {
                "type": "input_text",
                "text": (
                    "The following labeled images are the slides in deck order. "
                    "Use each image only for its matching slide number."
                ),
            }
        )
        for slide in slides:
            slide_number = slide.get("slide_number", "")
            title = slide.get("title") or f"Slide {slide_number}"
            images = (slide.get("images") or [])[:3]
            for index, image in enumerate(images, start=1):
                data_url = image.get("data_url")
                if not data_url:
                    continue
                suffix = f" image {index}" if len(images) > 1 else ""
                content.append(
                    {
                        "type": "input_text",
                        "text": f"Slide {slide_number}{suffix}: {title}",
                    }
                )
                content.append({"type": "input_image", "image_url": data_url, "detail": "high"})
    content.append({"type": "input_text", "text": prompt})
    return content


def expected_slides(context: Dict) -> List[Dict]:
    slides = context.get("slides") or []
    if slides:
        return slides
    return [{"slide_number": 1, "title": "Presentation", "text": "", "notes": ""}]


def raw_response(model: str, text: str) -> Dict:
    return {
        "mode": "llm",
        "model": model,
        "slides": [],
        "raw_text": text,
        "notices": ["OpenAI returned prose rather than structured JSON, so the raw response is shown."],
    }
